# Template that retrieves the Azure Databricks Workspace URL and an AAD Access Token that can be used to access it.
# By default, it uses the Azure Pipelines Principal that is automatically available when using an AzureCLI task.
# If the 'spClientId' and 'spClientSecret' parameters are set, then the script logs out the Pipelines Principal and then logs in with these credentials.
# 

parameters:
- name: azureSubscription
  displayName: 'Service connection name'
  type: string

- name: adbResourceGroup
  displayName: 'Azure Databricks Resource Group Name'
  type: string

- name: adbWorkspaceName
  displayName: 'Azure Databricks Workspace Name'
  type: string

- name: databricksUniqueId
  displayName: 'Databricks Unique Id'
  type: string
  default: '2ff814a6-3304-4ab8-85cb-cd0e6f879c1d'

- name: spClientId
  displayName: '(Optional) Service Principal Client Id to be used for login'
  type: string
  default: ''

- name: spClientSecret
  displayName: '(Optional) Service Principal Client Secret to be used for login'
  type: string
  default: ''

- name: scriptsLocation
  displayName: 'Location of Scripts'
  type: string


steps:
- task: AzureCLI@2
  displayName: 'Get Workspace URL'
  inputs:
    azureSubscription: '${{ parameters.azureSubscription }}'
    scriptType: 'bash'
    scriptPath: '${{ parameters.scriptsLocation }}/getWorkspaceUrl.sh'
    arguments: '"${{ parameters.adbResourceGroup }}" "${{ parameters.adbWorkspaceName }}"'

- task: AzureCLI@2
  displayName: 'Get AAD Access Token'
  inputs:
    azureSubscription: '${{ parameters.azureSubscription }}'
    scriptType: 'bash'
    scriptPath: '${{ parameters.scriptsLocation }}/getAADAccessToken.sh'
    arguments: '"${{ parameters.databricksUniqueId }}" "${{ parameters.spClientId }}" "${{ parameters.spClientSecret }}"'
